default_stages: ['commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: requirements-txt-fixer
- repo: https://github.com/NixOS/nixfmt
  rev: master
  hooks:
    -   id: nixfmt
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        args: ['-l', '100']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: ['-aa', '--max-line-length=100', "--in-place"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: ['--py311-plus']
- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
        args: ['--py39-plus']
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        args: ['--max-line-length=100']
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    -   id: bandit
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
-   repo: https://github.com/commitizen-tools/commitizen
    rev: 'v3.29.0'
    hooks:
    -   id: commitizen
